backend:
  name: github
  branch: master
  # open_authoring: true
  repo: maxogden/trailangeles
  auth_scope: repo
media_folder: "src/static/img"
public_folder: "/static/img"

local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Places"
    name: "places"
    extension: "json"
    editor:
      preview: true
    files:
      - file: "src/_data/places.json"
        label: "Places"
        name: "places"
        widget: "object"
        hint: "test"
        collapsed: false
        fields:
          - label: Places
            name: places
            widget: list
            collapsed: false
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Location, name: location, widget: map }
              - { label: Description, name: description, widget: string }
              - { label: ID, name: id, widget: id }
              - { label: Mapbox Maki Icon Name, name: maki, widget: string, required: false, hint: "View them here https://labs.mapbox.com/maki-icons/" }
  - label: "Trails Data"
    name: "trails"
    extension: "json"
    editor:
      preview: true
    files:
      - file: "src/_data/trails.json"
        label: "Trails"
        name: "trails"
        widget: "object"
        collapsed: false
        fields:
          - label: Trails
            name: trails
            widget: list
            collapsed: false
            fields:
              - { label: Name, name: name, widget: string }
              -
                label: "Area"
                name: "area"
                widget: "select"
                options:
                  - { label: "Altadena", value: "ALT" }
                  - { label: "Backcountry", value: "BACK" }
                  - { label: "Sierra Madre", value: "SM" }
              - { label: Slug, name: slug, widget: string }
              - { label: ID, name: id, widget: id }
              - { label: OsmWayId, name: osmwayid, widget: string, required: false, hint: "The numeric id at the end of e.g. https://www.openstreetmap.org/way/178426128, this will import the tags for that way on osm every time the site builds" }
              - { label: OsmTags, name: osmtags, widget: hidden, required: false }
              - {
                  label: Places,
                  name: places,
                  widget: relation,
                  collection: places,
                  file: 'places',
                  valueField: places.*.id,
                  displayFields: [places.*.name],
                  searchFields: [places.*.name],
                  multiple: true,
                  required: false,
                }
  - label: "Orgs Data"
    name: "orgs"
    extension: "json"
    editor:
      preview: true
    files:
      - file: "src/_data/orgs.json"
        label: "Organizations"
        name: "organizations"
        widget: "object"
        collapsed: false
        fields:
          - label: Organizations
            name: organizations
            widget: list
            collapsed: true
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Contact Name, name: contactName, widget: string }
              - { label: Contact Email, name: contactEmail, widget: string }
              - { 
                  label: Photo, 
                  name: photo, 
                  widget: file
                }
              - { label: Website, name: website, widget: string }
              - { label: Facebook, name: facebook, widget: string, required: false }
              - { label: Instagram, name: instagram, widget: string, required: false }
              - { label: Description, name: description, widget: text, required: false }
              - { label: Requirements, name: requirements, widget: text, required: false }
              - { label: Slug, name: slug, widget: string, required: true }
              - {
                  label: Trails,
                  name: trails,
                  widget: relation,
                  collection: trails,
                  file: 'trails',
                  valueField: trails.*.slug,
                  displayFields: [trails.*.name],
                  searchFields: [trails.*.name],
                  multiple: true,
                  required: false,
                }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
      - label: "Alert"
        name: "alert"
        file: "src/_data/alert.yaml"
        fields:
          - { label: Alert Text, name: text, widget: string }
          - { label: Alert Status, name: status, widget: boolean }
          - { label: Alert Link, name: string, widget: string }
          - { label: Alert Link Status, name: linkStatus, widget: boolean }
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

